FROM node
#Installing Google Chrome for end-to-end testing
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -y google-chrome-stable
#Setting up Angular Application
ENV ngPATH /usr/src/app
WORKDIR ${ngPATH}
COPY ./package.json ${ngPATH}/
RUN npm install -g @angular/cli
RUN npm install
COPY . .
